version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=words_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
